apiVersion: v1
kind: Pod
metadata:
  name: databases
  labels:
    db: databases
spec:
  containers:
  - name: mariadb
    image: docker.io/mariadb:10.6
    env:
    - name: MARIADB_USER
      value: foo
    - name: MARIADB_PASSWORD
      value: bar
    - name: MYSQL_ROOT_PASSWORD
      value: bar
    volumeMounts:
    - name: mariadb
      mountPath: /var/lib/mysql
    resources:
      limits:
        memory: "1Gi"

  - name: postgresql
    image: docker.io/bitnami/postgresql:15
    env:
    - name: POSTGRESQL_USERNAME
      value: foo
    - name: POSTGRESQL_PASSWORD
      value: bar
    volumeMounts:
    - name: postgresql
      mountPath: /bitnami/postgresql
    resources:
      limits:
        memory: "1Gi" 

  - name: adminer
    image: docker.io/adminer
    ports:
    - containerPort: 8080
      hostPort: 8080
      protocol: TCP
    env:
    - name: ADMINER_DESIGN
      value: dracula
  restartPolicy: Never
  dnsPolicy: Default
  volumes:
  - name: mariadb
    emptyDir:
      sizeLimit: 500Mi
  - name: postgresql
    emptyDir:
      sizeLimit: 500Mi