apiVersion: v1
kind: Pod
metadata:
  name: whoami
  labels:
    app: whoami
spec:
  containers:
  - name: whoami
    image: docker.io/traefik/whoami:latest
    ports:
    - containerPort: 8080
      protocol: TCP
    env:
    - name: WHOAMI_PORT_NUMBER
      value: 8080
  restartPolicy: Never
  dnsPolicy: Default